# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72e11237ce14ec6ec9e64c9ab1771f43143d1e790a9bddf0b62bbf2ff104ef23a2bc3621590a1af89de6429b167fa5a696d5d77cd9a294c670c3d36c980f82ac

test:
  secret_key_base: 3abd1765d43b024ff823f0357880ace8e037b37bcb31a43d8c376a7fc2f721f09c47efdfed1ad15200b35adfb7aaa2c6a96d5c8878b5aa5e1f28ec344e3f2143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
